name: SBOM generation
description: Generate CycloneDX and SPDX SBOMs for a built artifact containing SBOM precursor information (e.g. embedded using cargo-auditable)

inputs:
  file-to-scan:
    description: Path to the artifact to generate SBOMs for
    required: true

  artifact-name-prefix:
    description: Prefix for the generated SBOM artifact names
    required: true

runs:
  using: composite

  steps:
    - name: Generate CycloneDX SBOM
      uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
      with:
        file: ${{ inputs.file-to-scan }}
        format: cyclonedx-json
        artifact-name: ${{ inputs.artifact-name-prefix }}_sbom.cdx.json
        upload-release-assets: false

    - name: Generate SPDX SBOM
      uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
      with:
        file: ${{ inputs.file-to-scan }}
        format: spdx-json
        artifact-name: ${{ inputs.artifact-name-prefix }}_sbom.spdx.json
        upload-release-assets: false